name: EpicQuest
main: randy.epicquest.EpicMain
version: 3.5.4
depend: [Vault]
softdepend: [Heroes, Citizens, BarAPI]
commands:
  q:
    description: Quest commands
    usage: /<command>
    aliases: quest